export const ERROR_MSG = {
  API_KEY_MISSING: "ƛ :: ERROR - API KEY IS MISSING FROM '.env'",
  BASE_API_URL_MISSING: "ƛ :: ERROR - BASE API IS MISSING FROM '.env'",
  API_REQUEST_FAILED: "ƛ :: ERROR - FAILED TO COMPLETE API REQUEST",
  INVALID_RESPONSE: "ƛ :: ERROR - RECEIVED INVALID RESPONSE FROM API",
  GENERIC_ERROR: "ƛ :: ERROR - AN UNEXPECTED ERROR OCCURRED",
};
